name: CI & Deploy static site to Render

on:
  push:
    branches: [ "main" ]

jobs:
  ci-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Pruebas automatizadas: lint de HTML
      - name: Install HTMLHint
        run: npm i -g htmlhint
      - name: Lint HTML
        run: |
          if ls **/*.html >/dev/null 2>&1; then
            htmlhint "**/*.html"
          else
            echo "No HTML files found."
          fi

      # 2) Escaneo aplicable a estáticos: verificador de enlaces
      - name: Link check (lychee)
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --accept 200,206 --base . ./ --exclude-mail
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3) Construcción: no aplica en HTML puro (documentar como N/A)
      # 4) Despliegue a Render SOLO si todo lo anterior pasó
      - name: Trigger Render Deploy Hook
        if: ${{ success() }}
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
